### ISSUE TITLE
Migrate reusable functions from mobile-wallet to js-sdk

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/js-sdk#123]
There are a few useful functions from mobile-wallet that could be reused in desktop-wallet and other projects. Edit the following list as we find them:

* [ ] attoAlphToFiat
* [ ] getSuffix ([in Amount.tsx](https://github.com/alephium/mobile-wallet/blob/b3e217b1fa91bed4dd428ab77c8ea6a0a9b1a295/src/components/Amount.tsx#L77))
* [ ] formatFiatAmountForDisplay

**Comment by nop33** [comment]
As discussed on Slack, we'll just add `formatFiatAmountForDisplay` for now.
