### ISSUE TITLE
Discuss next SDK evolution and structure

### ISSUE THREAD

**Issue by mvaivre** [alephium/js-sdk#35]
Ref. https://github.com/alephium/explorer/pull/40/commits/e7bc72cf263bfc2eb1741416cdf4a44cd6959d6a#r773979231

We need to agree on what should be added to this project, and how to structure it.

An initial proposition would be:

- API methods
- Formatting helpers (numbers, amounts, errors etc.)
- Constants

Let's talk!

**Comment by mvaivre** [comment]
A lot of what is currently found in [utils](https://github.com/alephium/alephium-wallet/tree/master/src/utils) could actually be migrated to alephium-js

**Comment by mvaivre** [comment]
Following the migration work done by @nop33, let me close this now 🧨

**Comment by nop33** [comment]
@mvaivre I only moved number utils however, there's probably a lot more to be moved...

**Comment by mvaivre** [comment]
I was maybe a bit overoptimistic yeah, haha!
Especially since we could use this issue to talk about CLI work as well etc.

**Comment by nop33** [comment]
Closing since we moved to a [monorepo](https://github.com/alephium/alephium-frontend/) and we used shared packages there.
