### ISSUE TITLE
Transpile to JS

### ISSUE THREAD

**Issue by lf94** [alephium/js-sdk#46]
It would be very nice if the TS was transpiled to JS and saved in the project itself so people can directly reference it via `<script src="...">`, allowing themselves to avoid needing TypeScript, webpack, etc. We could then upload it to a CDN.

**Comment by nop33** [comment]
Agreed!

So, we would need to remove `dist/ ` from `.gitignore`, run `npm run compile`, and commit the files. And remember to do this every time we change the TS code. Or maybe have a CI pipeline that checks for changes in the TS code and compiles and commits JS code.

**Comment by polarker** [comment]
> Agreed!
> 
> So, we would need to remove `dist/ ` from `.gitignore`, run `npm run compile`, and commit the files. And remember to do this every time we change the TS code. Or maybe have a CI pipeline that checks for changes in the TS code and compiles and commits JS code.

Agree, a Github action is necessary if we want to add this

**Comment by polarker** [comment]
One was asking me if our SDK is ready for JS project?
