### ISSUE TITLE
Move devnet jar file and pid file to Home folder

### ISSUE THREAD

**Issue by polarker** [alephium/js-sdk#78]
Right now, both the jar file and pid file are stored locally, but it's a waist of space and it will cause trouble if there are are two devnet launched for two projects. We could resolve this by moving the jar file and pid file to Home folder.

Note: we need to test Windows as it's not easy to work with Home folder on windows.

**Comment by lf94** [comment]
Different projects may use different dev configurations. Will this still be possible?

**Comment by nop33** [comment]
Not relevant anymore, closing.
