### ISSUE TITLE
Fix TS warnings

### ISSUE THREAD

**Issue by mvaivre** [alephium/js-sdk#89]
Github is highlighting code issues in every PR we produce (see [here](https://github.com/alephium/js-sdk/pull/82/files#diff-0ae05afa209e5e4a1720704cbf9ecd5e63f439d409f03110f8d13cbf3aad591b) for instance).

Those warning are all concentrated in the `contract.ts` file. @polarker, could you take a look? Or would you like us to fix them? Thanks!

We will also make sure that tests are failing if there are outstanding warnings in the code (#90)

**Comment by polarker** [comment]
Please fix them for me. I am not familiar with the stack. Thanks!

**Comment by nop33** [comment]
Not relevant anymore, closing.
